### ISSUE TITLE
Laravel 6.0: Call to undefined function BeyondCode\SelfDiagnosis\Checks\starts_with()

### ISSUE THREAD

**Issue by axit-joost** [facade/ignition-self-diagnosis#1]
I'm getting a Symfony error page with a `Call to undefined function BeyondCode\SelfDiagnosis\Checks\starts_with()` after running the `composer require` on a fresh Laravel 6.0 project.

To reproduce:
- `laravel new my-project`
- `composer require facade/ignition-self-diagnosis`
- trigger an error, example:

`/route/web.php`:
```php
Route::get('/{amount}', function (int $amount) {
    return $amount;
});
```
Call with the route with anything but an integer.

![image](https://user-images.githubusercontent.com/13835397/64179267-263b1080-ce63-11e9-96f6-dd6b28267ea2.png)

**Comment by mpociot** [comment]
This should now be fixed with the latest release of the self-diagnosis package that we use under the hood.
